### NumPy Indexing and slicing of Vectors

In [1]:
import numpy as np

In [2]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr[6]

17

In [4]:
arr_slice = arr[1:5]
arr_slice

array([12, 13, 14, 15])

In [5]:
arr_slice = arr[2::2]
arr_slice

array([13, 15, 17, 19])

### NumPy Indexing and slicing of Matrix

In [6]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [7]:
arr[4]

array([21, 22, 23, 24, 25])

In [8]:
arr[0,4]

5

In [9]:
mat_slice = arr[0:3, 1:4]
mat_slice

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [10]:
arr[3: , 3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [11]:
arr[:, 3]

array([ 4,  9, 14, 19, 24, 29])

### Boolean Indexing

In [12]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [13]:
# check even or odd
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [14]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])