### Arithmetic Operations

In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [3]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [4]:
a1 // a2

array([0, 0, 0, 0, 0])

In [5]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [6]:
a1 * a2

array([ 6, 14, 24, 36, 50])

### Broadcasting

In [7]:
l = [10, 20, 30, 40, 50]
arr = np.array(l)
arr

array([10, 20, 30, 40, 50])

In [8]:
# I want add 10 in each element of the list 
for i in l:
    print(i + 10) # using list

20
30
40
50
60


In [9]:
#using array
arr + 10 # 1D

array([20, 30, 40, 50, 60])

In [10]:
# for 2D
arr2 = np.arange(1, 26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [11]:
arr2 = arr2 + 10 
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

### Deep and shallow copy

In [12]:
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [13]:
slice = a[:6]
slice = slice * 10  # shallow copy does not change original element of the variable
slice               # Deep copy does change the original element of the variable in list only 

array([10, 20, 30, 40, 50, 60])

In [14]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [15]:
# also we will do change like this\
a
b = a.copy()



In [16]:
b[0] = 99

In [17]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### Matrix Operartion

In [18]:
# Multiplication in matrix using dot product
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [19]:
a

array([[1, 2],
       [3, 4]])

In [20]:
b

array([[5, 6],
       [7, 8]])

In [21]:
# method 1st
a @ b

array([[19, 22],
       [43, 50]])

In [22]:
# method 2nd
np.dot(a, b)

array([[19, 22],
       [43, 50]])

In [23]:
# Transpose row become column
a.T

array([[1, 3],
       [2, 4]])