In [4]:
import numpy as np 

In [5]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [6]:
# data type
a = [1, 2, 3.56, "hello"]
a

[1, 2, 3.56, 'hello']

In [7]:
np.array(a) # convert a var into string

array(['1', '2', '3.56', 'hello'], dtype='<U32')

In [8]:
# Multi dimensional array
l = [[1,2,3], [4,5,6], [7,8,9]] # vector(always 1D)
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(l) # 2D array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Array generation function

In [10]:
# Array generation function (arange) same as python range function
arr = np.arange(1, 11, 2)
arr

array([1, 3, 5, 7, 9])

In [11]:
arr = np.zeros((6,6)) # give zeros in 2D form
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
arr = np.linspace(0, 1, 20)
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

### Random Generaton Function

In [13]:
# Generating random numbers (with using random labrary) with Array
arr = np.random.rand(6) # Normalization (0-1)
arr

array([0.28842519, 0.74961135, 0.26425418, 0.43292472, 0.60768037,
       0.20743814])

In [14]:
arr = np.random.randn(10) # Standardization (-3 - 3)
arr

array([-0.12103184,  0.74531679, -0.38484655,  0.57669118,  0.80001504,
       -0.13592021,  1.6154922 , -0.02469537, -0.14474347, -0.40245148])

In [15]:
arr = np.random.randint(6)
arr

3

In [16]:
arr = np.random.randint(10, 30, 10)
arr

array([19, 18, 17, 13, 10, 25, 17, 13, 13, 13])

### Array Attribute

In [17]:
arr = np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12],
               [13,14,15,16]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [18]:
arr.shape

(4, 4)

In [19]:
arr.size

16

In [20]:
arr.dtype

dtype('int32')

### Array methods

In [21]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [22]:
arr.min()

1

In [23]:
arr.max()

16

In [24]:
arr.sum()

136

In [25]:
np.sum(arr, axis= 0) # column wise sum

array([28, 32, 36, 40])

In [26]:
np.sum(arr, axis= 1) # row wise sum

array([10, 26, 42, 58])

In [27]:
arr.mean()

8.5

In [28]:
arr.std()

4.6097722286464435

In [29]:
arr.argmin()

0

In [30]:
arr.argmax()

15

### Reshaping and Resizing

In [31]:
arr = np.arange(1, 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [34]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])